kind: Service
apiVersion: v1
metadata:
  name: rfsc-ofertador-cloud-config-server
spec:
  selector:
    app: rfsc-ofertador-cloud-config-server
  ports:
    - name: http
      protocol: TCP
      nodePort: 32120
      port: 8888
      targetPort: 8888
  type: NodePort
