FROM qii404/git-server:latest

#docker build -t registryrfsc.azurecr.io/one-git-server:0.0.1


###
# create a user
#docker exec git-server create_user username password

# create a  repository for a user
#docker exec git-server create_project username repository

# clone
#git clone ssh://username@127.0.0.1:2022/git_codes/username/repository.git
# enter password

# push
#git push origin master
###
###